//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(AsignaPlanCobroMetadata))]
    public partial class AsignaPlanCobro
    {
        public int IdPlanCobro { get; set; }
        public int IdResidencia { get; set; }
        public string MesAsignado { get; set; }
        public string Estado { get; set; }
    
        public virtual PlanCobro PlanCobro { get; set; }
        public virtual Residencia Residencia { get; set; }
    }
}
