//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(IncidenciaMetadata))]
    public partial class Incidencia
    {
        public int IdIncidencia { get; set; }
        public int IdUsuario { get; set; }
        public string EstadoIncidencia { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaIncidencia { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
