//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(InformacionMetadata))]
    public partial class Informacion
    {
        public int IdInformacion { get; set; }
        public int IdTipoInformacion { get; set; }
        public string Descripcion { get; set; }
        public byte[] Imagen { get; set; }
    
        public virtual TipoInformacion TipoInformacion { get; set; }
    }
}
