//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ReservaAreaComunMetadata))]
    public partial class ReservaAreaComun
    {
        public int IdReserva { get; set; }
        public int IdResidencia { get; set; }
        public string AreaComun { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public string Horario { get; set; }
        public string Estado { get; set; }
    
        public virtual Residencia Residencia { get; set; }
    }
}
