//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructure.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(ResidenciaMetadata))]
    public partial class Residencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Residencia()
        {
            this.AsignaPlanCobro = new HashSet<AsignaPlanCobro>();
            this.ReservaAreaComun = new HashSet<ReservaAreaComun>();
        }
    
        public int IdResidencia { get; set; }
        public int IdUsuario { get; set; }
        public Nullable<int> CantPersonas { get; set; }
        public Nullable<int> CantAutos { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsignaPlanCobro> AsignaPlanCobro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservaAreaComun> ReservaAreaComun { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
